name: cototinder
description: Tinder-like app for cats
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  google_fonts: ^4.0.5
  get_it: ^7.6.4
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.9.0
  connectivity_plus: ^5.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  drift_dev: ^2.13.0
  build_runner: ^2.4.6